---
# =============================================================================
# IntensiCare API — PodDisruptionBudget
# =============================================================================
{{- if and .Values.api.enabled .Values.pdb.api.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "intensicare.fullname" . }}-api-pdb
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "intensicare.apiLabels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.api.minAvailable }}
  selector:
    matchLabels:
      {{- include "intensicare.apiSelectorLabels" . | nindent 6 }}
{{- end }}
