---
# =============================================================================
# IntensiCare API — ServiceAccount (IRSA)
# =============================================================================
{{- if .Values.serviceAccount.api.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.api.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "intensicare.apiLabels" . | nindent 4 }}
  {{- with .Values.serviceAccount.api.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
