---
# =============================================================================
# IntensiCare Frontend — Service
# =============================================================================
{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "intensicare.fullname" . }}-frontend
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "intensicare.frontendLabels" . | nindent 4 }}
  {{- with .Values.frontend.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    {{- include "intensicare.frontendSelectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
{{- end }}
