"""add antimicrobial_assessment + prophylaxis_assessment + alert_routing_rule tables

Revision ID: 0031
Revises: 0030
Create Date: 2026-07-07

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = "0031"
down_revision: Union[str, None] = "0030"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ── antimicrobial_assessment ──────────────────────────────────────────
    op.create_table(
        "antimicrobial_assessment",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("mpi_id", sa.String(length=64), nullable=False),
        sa.Column("criteria", postgresql.JSONB(), nullable=True,
                  comment="JSON array of AntimicrobialCriterion dicts evaluated in this assessment"),
        sa.Column("score", sa.Integer(), nullable=False,
                  comment="Total non-conformities (0-12)"),
        sa.Column("severity", sa.String(length=16), nullable=False,
                  comment="Severity band: NEUTRO, AMARELO, VERMELHO"),
        sa.Column("recommendation", sa.String(length=512), nullable=False,
                  comment="Clinical recommendation generated by the domain service (PT-BR)"),
        sa.Column("assessed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("assessed_by", sa.String(length=255), nullable=False,
                  comment="User or system that performed the assessment"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_antimicrobial_assessment_mpi_id"),
        "antimicrobial_assessment",
        ["mpi_id"],
        unique=False,
    )

    # ── prophylaxis_assessment ────────────────────────────────────────────
    op.create_table(
        "prophylaxis_assessment",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("mpi_id", sa.String(length=64), nullable=False),
        sa.Column("bundle_id", sa.String(length=32), nullable=False,
                  comment="Bundle identifier: lamgd, tev, hiperglicemia, mobilizacao, dispositivos"),
        sa.Column("criteria", postgresql.JSONB(), nullable=True,
                  comment="Array of {id, met, na} objects for each criterion"),
        sa.Column("status", sa.String(length=16), nullable=False, server_default="pending",
                  comment="Bundle status: complete, partial, pending, na"),
        sa.Column("score", sa.Integer(), nullable=False, server_default="0",
                  comment="Bundle score 0-100"),
        sa.Column("assessed_at", sa.DateTime(timezone=True), nullable=False,
                  comment="Timestamp of the last assessment"),
        sa.Column("assessed_by", sa.String(length=255), nullable=True,
                  comment="User who performed the assessment"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "mpi_id", "bundle_id",
            name="uq_prophylaxis_assessment_patient_bundle",
        ),
    )
    op.create_index(
        op.f("ix_prophylaxis_assessment_mpi_id"),
        "prophylaxis_assessment",
        ["mpi_id"],
        unique=False,
    )

    # ── alert_routing_rule ────────────────────────────────────────────────
    op.create_table(
        "alert_routing_rule",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("conditions", postgresql.JSONB(), nullable=False,
                  comment="Array of condition objects: {field, operator, value}"),
        sa.Column("actions", postgresql.JSONB(), nullable=False,
                  comment="Array of action objects: {type, channel, target, delay_minutes}"),
        sa.Column("enabled", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("priority", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_alert_routing_rule_tenant_id"),
        "alert_routing_rule",
        ["tenant_id"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_table("alert_routing_rule")
    op.drop_index(op.f("ix_prophylaxis_assessment_mpi_id"), table_name="prophylaxis_assessment")
    op.drop_table("prophylaxis_assessment")
    op.drop_index(op.f("ix_antimicrobial_assessment_mpi_id"), table_name="antimicrobial_assessment")
    op.drop_table("antimicrobial_assessment")
