"""Antimicrobial Stewardship — model for antimicrobial assessment persistence."""

from datetime import datetime

from sqlalchemy import BigInteger, DateTime, Integer, String
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from intensicare.core.database import Base


class AntimicrobialAssessment(Base):
    """Assessment record for antimicrobial stewardship evaluation.

    Stores the full criteria evaluation (12 criteria), score, severity,
    and clinical recommendation. Used by the stewardship domain service
    (domain_antimicrobiano.py) and exposed via REST API.

    Severity model: NEUTRO (0-3), AMARELO (4-7), VERMELHO (8-12).
    """

    __tablename__ = "antimicrobial_assessment"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    mpi_id: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    criteria: Mapped[list[dict] | None] = mapped_column(
        JSONB,
        nullable=True,
        comment="JSON array of AntimicrobialCriterion dicts evaluated in this assessment",
    )
    score: Mapped[int] = mapped_column(
        Integer, nullable=False, comment="Total non-conformities (0-12)"
    )
    severity: Mapped[str] = mapped_column(
        String(16),
        nullable=False,
        comment="Severity band: NEUTRO, AMARELO, VERMELHO",
    )
    recommendation: Mapped[str] = mapped_column(
        String(512),
        nullable=False,
        comment="Clinical recommendation generated by the domain service (PT-BR)",
    )
    assessed_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    assessed_by: Mapped[str] = mapped_column(
        String(255), nullable=False, comment="User or system that performed the assessment"
    )
