"""Boot-time sync of compiled YAML pathway definitions into Postgres.

The :class:`~intensicare.services.trilhas_engine.TrilhasEngine` is the
runtime source of truth for pathway evaluation (it loads and compiles the
YAML definitions under ``_work/alerts/pathways/`` in memory on every boot).
This module mirrors those compiled definitions into the ``pathways`` /
``pathway_criteria`` tables so that DB-backed reads (via
:class:`~intensicare.services.pathway_repository.PathwayRepository`) stay
content-addressed and in sync with the YAML source of truth, per
ADR-0020/ADR-0021.

Content hashing:
    The persisted ``definition_hash`` is always the *real*, freshly
    computed SHA-256 hash of the raw YAML dict (via
    :func:`~intensicare.services.trilhas_compiler.compute_content_hash`),
    never the ``pathway.content_hash`` value declared inside the YAML file
    itself. As of writing, every YAML definition ships with a fake
    placeholder ``content_hash`` (e.g.
    ``sha256:000...000b``) — trusting it would poison the content-addressed
    upsert (every boot would look unchanged). When a YAML's declared hash
    disagrees with the computed one, a WARNING is logged and the pathway's
    slug is recorded in :attr:`SyncReport.hash_mismatches` so the drift is
    visible without blocking boot.

Failure policy:
    A failure syncing one pathway (e.g. a malformed criterion, a DB error
    scoped to a single upsert) is caught, logged, and recorded in
    :attr:`SyncReport.failed` — it does not abort the sync of the
    remaining pathways. The caller (application lifespan) is responsible
    for deciding whether a failed sync run as a whole should block boot
    (per spec: it should not — only the engine's own zero-active-pathways
    RuntimeError is allowed to abort boot).
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession

from intensicare.services.pathway_repository import PathwayRepository
from intensicare.services.trilhas_compiler import compute_content_hash
from intensicare.services.trilhas_engine import TrilhasEngine

logger = logging.getLogger(__name__)


@dataclass
class SyncReport:
    """Outcome of a single boot-time YAML → DB pathway definitions sync."""

    synced: int = 0
    skipped: int = 0
    failed: list[str] = field(default_factory=list)
    hash_mismatches: list[str] = field(default_factory=list)


async def sync_pathway_definitions(db: AsyncSession, engine: TrilhasEngine) -> SyncReport:
    """Upsert every pathway definition loaded by ``engine`` into Postgres.

    For each :class:`~intensicare.services.trilhas_engine.PathwayDefinition`
    held by ``engine``:

    1. Recompute the real content hash from the raw YAML dict
       (``pdef.to_raw()``) and compare it against the ``content_hash``
       declared inside the YAML — a mismatch is logged (WARNING) and
       recorded, but does not block the upsert.
    2. Upsert the definition via
       :meth:`PathwayRepository.upsert_pathway_definition`, content-addressed
       by the real hash. Pathways that failed predicate compilation are
       synced with ``active=False`` (the engine already reflects that in
       ``pdef.active``) rather than being skipped — the DB should mirror
       what the engine actually loaded, deactivated pathways included.
    3. After all upserts, if any definition actually changed, resync the
       ``pathways.id`` sequence to ``MAX(id)`` — pathway ids are supplied
       explicitly (content-addressed, not autogenerated) by the upsert, so
       the sequence would otherwise drift behind and collide with the next
       autogenerated insert.

    Does not commit — the caller owns the transaction boundary.

    Args:
        db: Open async session (uncommitted).
        engine: A fully-initialized TrilhasEngine (already loaded/compiled).

    Returns:
        SyncReport summarizing what happened.
    """
    report = SyncReport()
    repo = PathwayRepository(db)

    for pdef in engine.get_pathways():
        try:
            raw = pdef.to_raw()
            real_hash = compute_content_hash(raw)

            declared_hash = (raw.get("pathway") or {}).get("content_hash") or None
            if declared_hash and declared_hash != real_hash:
                logger.warning(
                    "Pathway '%s' (id=%d): declared pathway.content_hash (%s) does "
                    "not match the computed content hash (%s) — YAML content_hash "
                    "is stale or a placeholder; persisting the computed hash.",
                    pdef.slug, pdef.id, declared_hash, real_hash,
                )
                report.hash_mismatches.append(pdef.slug)

            existing = await repo.get_pathway(pdef.id)
            already_synced = existing is not None and existing.definition_hash == real_hash

            meta = {
                "id": pdef.id,
                "name": pdef.name,
                "slug": pdef.slug,
                "description": pdef.description,
                "active": pdef.active,
            }

            await repo.upsert_pathway_definition(
                meta=meta,
                definition_hash=real_hash,
                states=pdef.states,
                criteria=pdef.criteria,
            )

            if already_synced:
                report.skipped += 1
            else:
                report.synced += 1
        except Exception as exc:  # noqa: BLE001 - one bad definition must not sink the rest
            logger.error(
                "Failed to sync pathway definition '%s' (id=%s): %s",
                pdef.slug, pdef.id, exc, exc_info=True,
            )
            report.failed.append(pdef.slug or str(pdef.id))

    if report.synced:
        await _resync_pathways_id_sequence(db)

    return report


async def _resync_pathways_id_sequence(db: AsyncSession) -> None:
    """Advance ``pathways``' PK sequence past the highest explicit id used.

    ``upsert_pathway_definition`` inserts with an explicit ``id`` (the
    pathway id declared in YAML), bypassing the sequence entirely. Left
    alone, the sequence stays at its initial value and a future plain
    ``INSERT`` (no explicit id) would collide with an existing row.

    The sequence name is resolved dynamically via
    ``pg_get_serial_sequence`` rather than hardcoded, since the exact name
    depends on how the column's default was declared (``Identity`` vs.
    implicit ``Serial``/``BigInteger`` + ``nextval`` default).
    """
    seq_row = await db.execute(text("SELECT pg_get_serial_sequence('pathways', 'id')"))
    seq_name = seq_row.scalar_one_or_none()
    if not seq_name:
        logger.warning(
            "pathways.id has no associated sequence (pg_get_serial_sequence "
            "returned NULL) — skipping sequence resync."
        )
        return

    await db.execute(
        text("SELECT setval(:seq_name, (SELECT COALESCE(MAX(id), 1) FROM pathways))").bindparams(
            seq_name=seq_name
        )
    )
