---
# =============================================================================
# IntensiCare Frontend — ClusterIP Service
# =============================================================================
apiVersion: v1
kind: Service
metadata:
  name: intensicare-frontend
  namespace: intensicare
  labels:
    app.kubernetes.io/name: intensicare-frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: intensicare-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: intensicare-frontend
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
