---
# =============================================================================
# IntensiCare API — ClusterIP Service
# =============================================================================
apiVersion: v1
kind: Service
metadata:
  name: intensicare-api
  namespace: intensicare
  labels:
    app.kubernetes.io/name: intensicare-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: intensicare-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: intensicare-api
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
    - name: websocket
      port: 8001
      targetPort: http
      protocol: TCP
